services:
  backend:
    build: ./
    networks:
      - pizza-network
    ports:
      - "${BACKEND_PORT}:5000"
  
  frontend:
    build: ./ui
    networks:
      - pizza-network
    ports:
      - "${FRONTEND_PORT}:80"

networks:
  pizza-network:
